# -*- coding: utf-8 -*-
"""sports-ball-image-classifier-with-99-accuracy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jScbh5p5iI4TjHhZfI5IakcJ-zQE8Ui0

## **Import Libraries**
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from sklearn.model_selection import train_test_split

import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adamax
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.metrics import classification_report, confusion_matrix

"""## **Data Preparation & Preprocessing**

### Creating DataFrames for Training and Testing Sets
"""

train_dir = train_dir = r"C:\Users\DELL\OneDrive\Documents\Python Tasks\Scikit-learn\Sports_ball_classifier\train"

filepaths = []
labels = []

folds = os.listdir(train_dir)

for fold in folds:
    foldpath = os.path.join(train_dir, fold)

    files = os.listdir(foldpath)
    for f in files:
        fpath = os.path.join(foldpath, f)

        filepaths.append(fpath)
        labels.append(fold)

train_df = pd.DataFrame(data={'filepaths':filepaths, 'labels':labels})
train_df

test_dir =r"C:\Users\DELL\OneDrive\Documents\Python Tasks\Scikit-learn\Sports_ball_classifier\test"

filepaths = []
labels = []

folds = os.listdir(train_dir)

for fold in folds:
    foldpath = os.path.join(train_dir, fold)

    files = os.listdir(foldpath)
    for f in files:
        fpath = os.path.join(foldpath, f)

        filepaths.append(fpath)
        labels.append(fold)

tst_df = pd.DataFrame(data={'filepaths':filepaths, 'labels':labels})
tst_df

valid_df, test_df = train_test_split(tst_df, test_size=0.5, random_state=42,shuffle=True)

"""### Exploring Class Distribution with Sample Images"""

from PIL import Image

# Assuming train_df has 'filepath' and 'labels' columns
# Get a sample image for each class from train_df
sample_images = {}

# Loop through train_df to get one image per class
for index, row in train_df.iterrows():
    class_label = row['labels']
    if class_label not in sample_images:
        # Load the image and store it if this class is not yet in sample_images
        image = Image.open(row['filepaths'])
        sample_images[class_label] = image

    # Stop if we have one image for each class
    if len(sample_images) == 15:
        break

# Plot the sample images
fig, axes = plt.subplots(3, 5, figsize=(15, 10))  # Adjust grid size if needed
fig.suptitle('One Sample Image for Each Class', fontsize=16)

# Display each image with its class label
for idx, (class_label, image) in enumerate(sample_images.items()):
    ax = axes[idx // 5, idx % 5]  # Position in the grid
    ax.imshow(image)
    ax.axis("off")
    ax.set_title(class_label)

plt.tight_layout()
plt.show()

#Display some sample images from the DataFrame
def display_sample_images(dataframe, n=5):
    plt.figure(figsize=(12, 12))

    # Select n random samples from the dataframe
    sample_df = dataframe.sample(n=n).reset_index(drop=True)

    for i in range(n):
        filepath = sample_df.loc[i, 'filepaths']
        label = sample_df.loc[i, 'labels']

        # Read and display the image
        image = cv2.imread(filepath)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB for correct color display

        plt.subplot(1, n, i+1)
        plt.imshow(image)
        plt.title(label, fontsize=12)
        plt.axis("off")

    plt.tight_layout()
    plt.show()

# Call the function with the dataframe
display_sample_images(train_df, n=5)

"""### Creating Data Generators with Augmentation"""

tr_gen = ImageDataGenerator(rotation_range=0.45,
                            width_shift_range=0.1,
                            height_shift_range=0.1,
                            zoom_range=0.4,
                            horizontal_flip=True,
                            vertical_flip=True)

ts_gen = ImageDataGenerator(rotation_range=0.45,
                            width_shift_range=0.1,
                            height_shift_range=0.1,
                            zoom_range=0.4,
                            horizontal_flip=True,
                            vertical_flip=True)

train_gen = tr_gen.flow_from_dataframe(train_df,
                                       x_col='filepaths',
                                       y_col='labels',
                                       target_size=(224, 224),
                                       color_mode='rgb',
                                       class_mode='categorical' ,
                                       batch_size=32)

test_gen = ts_gen.flow_from_dataframe(test_df,
                                      x_col='filepaths',
                                      y_col='labels',
                                      target_size=(224, 224),
                                      color_mode='rgb',
                                      class_mode='categorical' ,
                                      batch_size=32)

val_gen = ImageDataGenerator(rotation_range=0.45,
                            width_shift_range=0.1,
                            height_shift_range=0.1,
                            zoom_range=0.4,
                            horizontal_flip=True,
                            vertical_flip=True)

valid_gen = val_gen.flow_from_dataframe(valid_df,
                                      x_col='filepaths',
                                      y_col='labels',
                                      target_size=(224, 224),
                                      color_mode='rgb',
                                      class_mode='categorical' ,
                                      batch_size=32)

"""## **Building the Deep Learning Model**

### Creating a Sequential Model with EfficientNetB3 as Base
"""

base_model = tf.keras.applications.EfficientNetB3(
    include_top=False,
    weights=None,
    input_tensor=None,
    input_shape=(224,224,3,),
    pooling= "avg",
    classes=1000,
    classifier_activation="softmax",

)

model = Sequential([
    base_model,
    Flatten(),


    Dense(256,activation='relu'),
    Dense(128,activation='relu'),
    Dense(64,activation='relu'),
    Dense(32,activation='relu'),
    Dense(15,activation='softmax'),
])

model.compile(optimizer=Adamax(learning_rate=0.001),loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

history = model.fit(train_gen, validation_data = valid_gen, epochs=5)

"""### Model Evaluation Results"""

train_score = model.evaluate(train_gen)
valid_score = model.evaluate(valid_gen)
test_score = model.evaluate(test_gen)

print("Train Loss: ", train_score[0])
print("Train Accuracy: ", train_score[1])
print('-' * 20)
print("Validation Loss: ", valid_score[0])
print("Validation Accuracy: ", valid_score[1])
print('-' * 20)
print("Test Loss: ", test_score[0])
print("Test Accuracy: ", test_score[1])

"""### Model Summary"""

results_df = pd.DataFrame({
    "Dataset": ["Train", "Validation", "Test"],
    "Loss": [train_score[0], valid_score[0], test_score[0]],
    "Accuracy": [train_score[1], valid_score[1], test_score[1]]
})

results_df
